@default_files = ('barnholdt.grunbaum.jorgensen.3');

## WINDOWS
#$pdf_previewer = "\"C:\\Program Files (x86)\\SumatraPDF\\SumatraPDF.exe\" \"-reuse-instance\""; 

## LINUX
$pdf_previewer = "start evince";

$pdf_update_method = 0;
$pdf_use = 1;
$bibtex_use = 1;
$dvi_mode = 0;
$postscript_mode = 0;
$recorder = 1;
$view = "pdf";
$preview_mode = 1;
